services:
  redis:
    image: redis:7-alpine
    container_name: meeting-rest-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build: ./server
    container_name: meeting-rest-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    command: uvicorn main:socket_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app
    restart: unless-stopped

volumes:
  redis_data:
